name: Tag and Publish
on:
  push:
    branches:
      - main
jobs:
  tagAndPublish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      
      - name: Tag
        id: tag
        uses: salsify/action-detect-and-tag-new-version@v2

      - name: Setup Node.js
        if: steps.tag.outputs.tag
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        if: steps.tag.outputs.tag
        run: yarn install
      
      - name: CI Double Check
        if: steps.tag.outputs.tag
        run: yarn ci

      - name: Build
        if: steps.tag.outputs.tag
        run: yarn build

      - name: Publish
        if: steps.tag.outputs.tag
        run: echo "publishing release ${{ steps.tag.outputs.tag }} " && yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}