name: Tag and Publish
on:
  push:
    branches:
      - main
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      
      - name: Tag
        id: tag
        uses: salsify/action-detect-and-tag-new-version@v2
  
  publish:
    if: ${{ steps.tag.outputs.tag }}
    runs-on: ubuntu-latest
    steps: 
      - name: Install
        run: yarn install
      
      - name: CI Double Check
        run: yarn ci

      - name: Build
        run: yarn build

      - run: echo "publishing release ${{ steps.tag.outputs.tag }} "

      - name: Publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}